"""Optional but runnable AlphaMaze LoRA/SFT entry point for the course maze data.

Input: artifacts/train/hf_sft_messages.jsonl generated by scripts/generate_dataset.py.
Output: a PEFT LoRA adapter directory. On an 8GB RTX 4060 Laptop, start with
--max-samples 64 --max-steps 5 to verify the full download/GPU/training path.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import os


def main() -> None:
    parser = argparse.ArgumentParser(description="LoRA SFT for Menlo/AlphaMaze-v0.2-1.5B on course-rule mazes.")
    parser.add_argument("--model", default="Menlo/AlphaMaze-v0.2-1.5B")
    parser.add_argument("--data", default="artifacts/train/hf_sft_messages.jsonl")
    parser.add_argument("--out", default="artifacts/hf_lora/alphamaze-course-lora")
    parser.add_argument("--max-samples", type=int, default=128)
    parser.add_argument("--max-steps", type=int, default=20)
    parser.add_argument("--epochs", type=float, default=1.0)
    parser.add_argument("--lr", type=float, default=2e-4)
    args = parser.parse_args()

    os.environ.setdefault("HF_HUB_DISABLE_XET", "1")

    try:
        import torch
        from datasets import load_dataset
        from peft import LoraConfig
        from transformers import AutoModelForCausalLM, AutoTokenizer
        from trl import SFTConfig, SFTTrainer
    except Exception as exc:  # pragma: no cover - optional dependency path
        raise SystemExit(
            "Missing optional HF training dependencies. Install transformers datasets peft trl accelerate first."
        ) from exc

    ds = load_dataset("json", data_files=str(Path(args.data).resolve()))["train"]
    if args.max_samples and len(ds) > args.max_samples:
        ds = ds.select(range(args.max_samples))

    tokenizer = AutoTokenizer.from_pretrained(args.model, trust_remote_code=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    dtype = torch.float16 if torch.cuda.is_available() else torch.float32
    model = AutoModelForCausalLM.from_pretrained(
        args.model,
        torch_dtype=dtype,
        device_map="auto" if torch.cuda.is_available() else None,
        trust_remote_code=True,
        low_cpu_mem_usage=True,
        attn_implementation="eager",
    )
    model.config.use_cache = False

    def format_example(example):
        messages = example["messages"]
        if getattr(tokenizer, "chat_template", None):
            return tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=False)
        return f"User:\n{messages[0]['content']}\nAssistant:\n{messages[1]['content']}"

    peft_config = LoraConfig(
        r=8,
        lora_alpha=16,
        lora_dropout=0.05,
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
        task_type="CAUSAL_LM",
    )
    train_args = SFTConfig(
        output_dir=args.out,
        num_train_epochs=args.epochs,
        max_steps=args.max_steps,
        per_device_train_batch_size=1,
        gradient_accumulation_steps=8,
        learning_rate=args.lr,
        logging_steps=1,
        save_strategy="steps",
        save_steps=max(1, args.max_steps),
        max_length=1536,
        packing=False,
        fp16=torch.cuda.is_available(),
        bf16=False,
        gradient_checkpointing=True,
        report_to="none",
        remove_unused_columns=False,
    )
    trainer = SFTTrainer(
        model=model,
        args=train_args,
        train_dataset=ds,
        processing_class=tokenizer,
        peft_config=peft_config,
        formatting_func=format_example,
    )
    trainer.train()
    trainer.save_model(args.out)
    tokenizer.save_pretrained(args.out)
    print(f"saved LoRA adapter: {args.out}")


if __name__ == "__main__":
    main()
